export enum PlayerState {
  RUNNING = 'RUNNING',
  LANE_CHANGE_LEFT = 'LANE_CHANGE_LEFT',
  LANE_CHANGE_RIGHT = 'LANE_CHANGE_RIGHT',
  JUMPING = 'JUMPING',
  FALLING = 'FALLING',
  SLIDING = 'SLIDING',
  STUMBLING = 'STUMBLING',
  CRASHED = 'CRASHED',
  REVIVING = 'REVIVING',
}
